### ISSUE TITLE
About the min algorithm

### ISSUE THREAD

**Issue by jzx-bitdb** [sylab/cacheus#13]
What is the principle of Min algorithm? Is there any relevant literature？ I can't understand the meaning of your code. Thank you very much!!

**Comment by xiangshaocheng** [comment]
I want to know if the statement "num_classes = 6" on line 10 of model.py is correct, because there are 51 classes of samples in HMDB-51 dataset, and I think this variable should be set to 51. After setting it to 51, the program runs smoothly.

**Comment by sylab** [comment]
It's the Belady's MIN algorithm: https://inria.hal.science/hal-01199424/document
