### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by JerryHsh** [sylab/cacheus#9]
HI
I am an undergraduate from Hust and I am very interested on your paper Cacheus.
However, after I downloaded Fiu trace and your source code, the demo doesn't work. When you run alecar6 experiment, you will find that the request function here is wrong and an TypeError will be raised for 

______place where the request is called_______
        for lba, write, _ in self.reader.read():
            op, evicted = alg.request(lba, _ )

_____alecar6 request_____
    def request(self, oblock):
        miss = True
        evicted = None

The number of the parameter here simply don't match with each other here. 
It seems that the parameter ts here is missing.

**Comment by sylab** [comment]
Fixed in commit 09a2182d5263e7ae20619050f19a555e19e974ce
